print ("WLECOME TO BAND NAME GENERATOR")
City = input("WHICH CITY YOU GROW UP IN \n")
print(City)
pet = input("WHAT IS THE PET NAME \n")
print(pet)
print ("YOUR BANED NAME COULD BE:-" + City +" "+ pet)